In [1]:
import numpy as np

In [2]:
v = np.ndarray([1,1,2,3])
b1 = np.ndarray([1,0,0,0])
np.dot([1,1,2,3],[0,1,2,0])

5

In [3]:
a = np.array([[1,1,1],[3,2,1],[2,1,2]])
np.linalg.inv(a)

array([[-1.5,  0.5,  0.5],
       [ 2. ,  0. , -1. ],
       [ 0.5, -0.5,  0.5]])

In [11]:
c = np.array([[7, 1],[-3, 0]])
cinv = np.linalg.inv(c)
t = np.array([[2,7],[0,-1]])

In [12]:
np.matmul(np.matmul(cinv, t), c)

array([[-1.00000000e+00,  0.00000000e+00],
       [ 1.77635684e-15,  2.00000000e+00]])

In [15]:
c = np.array([[1,0],[1,1]])
cinv = np.linalg.inv(c)
t = np.array([[1,0],[2,-1]])
np.matmul(np.matmul(cinv, t), c)

array([[ 1.,  0.],
       [ 0., -1.]])

In [16]:
c = np.array([[1,1],[1,2]])
cinv = np.linalg.inv(c)
d = np.array([[125,0],[0,64]])
np.matmul(c, np.matmul(d,cinv))

array([[186., -61.],
       [122.,   3.]])

In [17]:
c = np.array([[7,1],[-3,0]])
cinv = np.linalg.inv(c)
d = np.array([[-1,0],[0,8]])
np.matmul(c, np.matmul(d,cinv))

array([[ 8., 21.],
       [ 0., -1.]])

In [22]:
1 + np.sqrt(5)/2, 1 - np.sqrt(5)/2

(2.118033988749895, -0.1180339887498949)

In [4]:
import numpy as np
a = np.array([[0,1,0,0],
                [1,0,0,0],
                [0,0,0,1],
                [0,0,1,0]
               ])
np.linalg.det(a)

1.0

In [10]:
c = np.array([[-1-np.sqrt(3), -1 + np.sqrt(3)],[1, 1]])
a = np.array([[3/2, -1],[-1/2, 1/2]])
invC = np.linalg.inv(c)
d = invC @ a @ c
d1 = np.matmul(invC, np.matmul(a,c))
print(d)
d1

[[1.86602540e+00 5.55111512e-17]
 [5.55111512e-17 1.33974596e-01]]


array([[1.86602540e+00, 5.20417043e-17],
       [0.00000000e+00, 1.33974596e-01]])

In [14]:
dd = d @ d
aa = c @ dd @ invC
aa

array([[ 2.75, -2.  ],
       [-1.  ,  0.75]])

In [16]:
checkAA = np.array([[11/4, -2], [-1, 3/4]])
checkAA

array([[ 2.75, -2.  ],
       [-1.  ,  0.75]])

In [18]:
x = np.array([[4,-5,6],
              [7,-8,6],
              [3/2,-1/2,-2]])
np.linalg.eig(x)


(array([ 1., -4., -3.]), array([[-0.6882472 , -0.66666667,  0.40824829],
        [-0.6882472 , -0.66666667, -0.40824829],
        [-0.22941573,  0.33333333, -0.81649658]]))